disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Universal Joy"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "initial.png"
description = "Play Beyond Barriers"

["params.author"]
name = "Universal Joy"
