[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "FOAivvAnRy"
weight = 9_999

[[main]]
name = "Blog"
pageRef = "blog"
identifier = "VrulG2K3uT"
weight = 9_999

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "y8JBWtUAKX"
weight = 9_999

[[footer]]
none = "none"

[[footer]]
name = "BluSky"
url = "https://pierceo.bsky.social"
identifier = "tAGtpGxTLT"
weight = 9_999

[[footer]]
name = "GitHub"
url = "https://github.com/Gristlan"
identifier = "iXuxMIzV37"
weight = 9_999
