baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Universal Joy'
theme = 'anatole'
[params]
description = "Welcome to Universal Joy\nPlay Beyond Barriers!"
profilePicture = "images/initial.png"
